---
title: C6310 | Microsoft Docs
ms.custom: ''
ms.date: 2018-06-30
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6310
helpviewer_keywords:
- C6310
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
caps.latest.revision: 15
author: corob-msft
ms.author: gewarren
manager: ghogen
ms.openlocfilehash: 82d8016331a8e849fc08e4b1e1357159d6fd3b2a
ms.sourcegitcommit: 55f7ce2d5d2e458e35c45787f1935b237ee5c9f8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 08/22/2018
ms.locfileid: "47552487"
---
# <a name="c6310"></a>C6310
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

이 항목의 최신 버전에서 찾을 수 있습니다 [C6310](https://docs.microsoft.com/visualstudio/code-quality/c6310)합니다.  
  
경고 C6310: 예외 필터에 잘못 된 상수가 예기치 않은 동작이 발생할 수 있습니다  
  
 이 메시지는 잘못 된 상수가 구조적된 예외 처리기의 필터 식에서 검색 되었음을 나타냅니다. 구조적된 예외 처리기의 필터 식에서 사용 하기 위해 정의 된 상수 다음과 같습니다.  
  
-   `EXCEPTION_CONTINUE_EXECUTION`  
  
-   `EXCEPTION_CONTINUE_SEARCH`  
  
-   `EXCEPTION_EXECUTE_HANDLER`  
  
 이러한 값은 런타임 헤더 파일 excpt.h에 정의 됩니다.  
  
 앞의 목록에 없는 상수를 사용 하 여 예기치 않은 동작이 발생할 수 있습니다.  
  
## <a name="example"></a>예제  
 다음 코드에서는이 경고를 생성합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
BOOL LimitExceeded();  
  
void fd( )  
{  
  __try   
  {  
    if (LimitExceeded())   
    {  
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);  
    }  
    else  
    {  
      // code   
    }  
  }   
  __except (EXCEPTION_ACCESS_VIOLATION)  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 이 경고를 해결 하려면 다음 코드를 사용 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
BOOL LimitExceeded();  
  
void fd( )  
{  
  __try   
  {  
    if (LimitExceeded())   
    {  
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);  
    }  
    else  
    {  
      // code   
    }  
  }   
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
  {  
    puts("Exception Occurred");  
  }  
}  
```



