---
title: C6312 | Microsoft Docs
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 766a3c670a41bb4f915c94c3f5d0df09fde11afe
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/16/2018
---
# <a name="c6312"></a>C6312
C6312 경고: 무한 루프가: try의 예외 필터 식에서 상수 EXCEPTION_CONTINUE_EXECUTION 사용-제외 하 고  
  
 이 경고는 상수를 사용 하는 나타냅니다 `EXCEPTION_CONTINUE_EXECUTION` (또는-1로 계산 되는 다른 상수) 구조적된 예외 처리기의 필터 식에 있습니다. 상수 값이 사용 `EXCEPTION_CONTINUE_EXECUTION` 무한 루프가 발생할 수 있습니다. 예를 들어 예외가 하드웨어에 의해 발생 하는 경우 예외를 발생 시킨 명령은 다시 시작 됩니다. 예외를 발생 시킨 주소를 계속 잘못 다른 예외가 발생 하 고 동일한 방식으로 처리 합니다. 이렇게 하면 무한 반복 됩니다.  
  
 명시적으로 호출 `RaiseException` 를 직접적 원인 무한 루프를 하지만 보호 된 블록에는 코드 실행을 계속 합니다. 예기치 않은 될 수이 고 경우에 무한 루프가 발생할 수 `RaiseException` 잘못 된 포인터 역참조를 피하기 위해 사용 되었습니다.  
  
 일반적으로 `EXCEPTION_CONTINUE_EXECUTION` 예외를 발생 시킨 포인터 또는 내부 메모리를 수정할 수 있는 필터 식에서 호출 하는 함수에서만 반환 해야 합니다.  
  
## <a name="example"></a>예제  
 다음 코드에서는이 경고를 생성합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 이 경고를 해결 하려면 다음 코드를 사용 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```