---
title: C6318 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6318
helpviewer_keywords: C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
caps.latest.revision: "13"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: 1dc86ec8f0426d34e9fcc5fe68bbb34a161b47d0
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 12/22/2017
---
# <a name="c6318"></a>C6318
C6318 경고: 잘못 정의 __try /\__except:에서 상수 EXCEPTION_CONTINUE_SEARCH 또는 0 예외 필터 식으로 계산 되는 다른 상수를 사용 합니다. 예외 처리기 블록의 코드가 실행 되지 않습니다.  
  
 이 구조적된 예외 처리기의 보호 된 블록에서 예외가 발생 하는 경우 예외는 처리 하지 않은 수 때문에이 경고는 나타냅니다 상수 `EXCECPTION_CONTINUE_SEARCH` 예외 필터 식에 사용 됩니다.  
  
 처리기 블록이 실행 되지 않기 때문에이 코드는 예외 처리기 블록 없이 보호 된 블록에 해당 합니다.  
  
## <a name="example"></a>예  
 다음 코드에서는이 경고를 생성합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 이 경고를 해결 하려면 다음 코드를 사용 합니다.  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?  
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    puts("Access violation");  
  }  
}   
```  
  
## <a name="see-also"></a>참고 항목  
 [try-except 문](/cpp/cpp/try-except-statement)